/**
 * Golden tests for the Indonesian personal rule set.
 *
 * Every expected number here was worked by hand from the instrument named in
 * the test, not read back from the implementation. A golden test that was
 * generated by running the code proves only that the code is deterministic.
 */

import { describe, expect, it } from 'vitest';

import type { CurrencySpec } from './contract.js';
import {
  alternativeRegime,
  checkStatedTax,
  checkTaxId,
  confusableTaxes,
  consumptionTaxPaid,
  datePlausible,
  incomeTax,
  periodOf,
  personalAllowance,
  standardDeduction,
  taxFromInclusive,
  taxOnSale,
} from './interpreter.js';
import { formatLocalAmount, parseLocalAmount, reconcileTolerance } from './money.js';
import { ID_2026 } from './rules/id-2026.js';
import { inspectRules } from './verify.js';

const IDR = ID_2026.currency;

/** Compare ignoring the working scale's trailing zeros. */
const money = (s: string) => Number(s);

describe('the rules itself', () => {
  it('passes verification with no problems', () => {
    expect(inspectRules(ID_2026)).toEqual([]);
  });

  it('is a personal rules, so PPN is not recoverable and there is no PPN return', () => {
    // The two facts that follow from `scope: personal`, asserted together
    // because a rule set where they disagree describes two different taxpayers.
    expect(ID_2026.scope).toBe('personal');
    expect(ID_2026.consumptionTax.recoverable).toBe(false);
    expect(ID_2026.periods.consumptionTaxPeriod).toBe('none');
    expect(ID_2026.taxCodes.every((c) => c.claimsCredit === false)).toBe(true);
  });

  it('declares a posting-lag window and a bank-interest treatment', () => {
    // docs/STATEMENTS.md §7.4's last two rows — the parameters the contract
    // could not express until now.
    expect(ID_2026.statementRules.postingLagDays).toEqual({ min: 0, max: 3 });
    expect(ID_2026.statementRules.bankInterest.kind).toBe('final_withholding');
    expect(ID_2026.statementRules.bankInterest.rate).toEqual({ n: 20, d: 100 });
    // Final means final: not folded into the PPh 21 scale on the annual return.
    expect(ID_2026.statementRules.bankInterest.declaredOnReturn).toBe(false);
  });
});

describe('PPN — the 12%-on-11/12 structure', () => {
  it('takes 11/111 out of a tax-inclusive total, not 1/11', () => {
    // Rp 1,000,000 price + Rp 110,000 PPN. docs/INDONESIA.md §2.2.
    const r = taxFromInclusive(ID_2026, '1110000');
    expect(money(r.taxAmount)).toBe(110_000);
    // The Australian answer, for contrast: 1,110,000 / 11 = 100,909.09.
    expect(money(r.taxAmount)).not.toBe(Math.round(1_110_000 / 11));
  });

  it('breaks taxable + tax = inclusive, which is the whole finding', () => {
    // docs/INDONESIA.md §2.3. The faktur prints a DPP of 11/12 of the price,
    // so the document's own base plus its own tax does NOT re-add to what was
    // paid. Australia has no case where this is true.
    const r = taxFromInclusive(ID_2026, '1110000');
    expect(money(r.documentBase)).toBe(916_667); // 11/12 of 1,000,000, to the rupiah
    expect(money(r.netAmount)).toBe(1_000_000);
    expect(money(r.documentBase) + money(r.taxAmount)).not.toBe(1_110_000);
    // And the net — what was actually spent before tax — is not the DPP.
    expect(money(r.netAmount)).not.toBe(money(r.documentBase));
  });

  it('adds 11% to an ex-tax price even though the printed rate is 12%', () => {
    const r = taxOnSale(ID_2026, '1000000');
    expect(money(r.taxAmount)).toBe(110_000);
    expect(money(r.documentBase)).toBe(916_667);
  });

  it('never reports PPN as recoverable for a personal taxpayer', () => {
    expect(taxFromInclusive(ID_2026, '1110000').recoverable).toBe(false);
    expect(taxOnSale(ID_2026, '1000000').recoverable).toBe(false);
  });

  it('tolerates till rounding in rupiah, not in cents', () => {
    // §7.2: five cents is the wrong tolerance in a currency whose smallest
    // circulating unit is Rp 100. Five increments of Rp 100 = Rp 500.
    expect(money(reconcileTolerance(IDR))).toBe(500);

    const near = checkStatedTax(ID_2026, '1110000', '109800'); // Rp 200 out
    expect(near.withinTolerance).toBe(true);
    const far = checkStatedTax(ID_2026, '1110000', '100909'); // the 1/11 answer
    expect(far.withinTolerance).toBe(false);
    expect(money(far.expected)).toBe(110_000);
  });
});

describe('PB1 — the tax that is not PPN', () => {
  it('flags a restaurant tax line as confusable and non-recoverable', () => {
    // docs/INDONESIA.md §5. Australia has no second 10% tax on a docket, so
    // the existing reader has no concept for this and would bank it as GST.
    const found = confusableTaxes(ID_2026, ['SUBTOTAL', 'PB1', 'TOTAL']);
    expect(found).toHaveLength(1);
    expect(found[0]!.code).toBe('PB1');
    expect(found[0]!.recoverable).toBe(false);
    expect(found[0]!.why).toMatch(/never recoverable/i);
  });

  it('says nothing when no other tax token is present', () => {
    expect(confusableTaxes(ID_2026, ['SUBTOTAL', 'PPN', 'TOTAL'])).toEqual([]);
  });
});

describe('PTKP', () => {
  // PMK 101/2016, unchanged for 2026.
  it.each([
    ['TK/0', { married: false, dependants: 0 }, 54_000_000],
    ['TK/1', { married: false, dependants: 1 }, 58_500_000],
    ['K/0', { married: true, dependants: 0 }, 58_500_000],
    ['K/1', { married: true, dependants: 1 }, 63_000_000],
    ['K/2', { married: true, dependants: 2 }, 67_500_000],
    ['K/3', { married: true, dependants: 3 }, 72_000_000],
  ])('%s is Rp %s', (_label, status, expected) => {
    expect(money(personalAllowance(ID_2026, status).amount)).toBe(expected);
  });

  it('caps countable dependants at three without rejecting a fourth child', () => {
    // The statutory limit is on what may be COUNTED, not on how many people
    // someone supports. Refusing the input would be wrong.
    const four = personalAllowance(ID_2026, { married: true, dependants: 4 });
    expect(four.dependantsCounted).toBe(3);
    expect(money(four.amount)).toBe(72_000_000);
  });

  it('adds the spouse allowance when incomes are combined (K/I/0)', () => {
    const ki = personalAllowance(ID_2026, {
      married: true,
      dependants: 0,
      spouseIncomeCombined: true,
    });
    expect(money(ki.amount)).toBe(112_500_000); // 54m + 4.5m + 54m
  });
});

describe('biaya jabatan', () => {
  it('is 5% of gross', () => {
    const d = standardDeduction(ID_2026, 'biaya_jabatan', '60000000')!;
    expect(money(d.amount)).toBe(3_000_000);
    expect(d.capped).toBe(false);
  });

  it('caps at Rp 6,000,000 a year', () => {
    const d = standardDeduction(ID_2026, 'biaya_jabatan', '300000000')!;
    expect(money(d.amount)).toBe(6_000_000);
    expect(d.capped).toBe(true);
  });

  it('caps a part year against the monthly cap, not the annual one', () => {
    // Four months of employment is capped at 4 x 500,000, not 6,000,000.
    const d = standardDeduction(ID_2026, 'biaya_jabatan', '100000000', 4)!;
    expect(money(d.amount)).toBe(2_000_000);
    expect(d.capped).toBe(true);
  });
});

describe('PPh 21 on the ordinary scale', () => {
  it('taxes a Rp 120m single employee at Rp 3,000,000', () => {
    // gross 120,000,000
    //   less biaya jabatan 6,000,000 (5% = 6,000,000, exactly at the cap)
    //   less PTKP TK/0     54,000,000
    //   taxable            60,000,000  -> all in the 5% band
    //   tax                 3,000,000
    const r = incomeTax(ID_2026, {
      grossIncome: '120000000',
      status: { married: false, dependants: 0 },
      deductionCodes: ['biaya_jabatan'],
    });
    expect(money(r.netIncome)).toBe(114_000_000);
    expect(money(r.allowance)).toBe(54_000_000);
    expect(money(r.taxableIncome)).toBe(60_000_000);
    expect(money(r.taxPayable)).toBe(3_000_000);
  });

  it('crosses into the 15% band correctly for K/2 on Rp 300m', () => {
    // gross 300,000,000
    //   less biaya jabatan   6,000,000 (capped)
    //   less PTKP K/2       67,500,000
    //   taxable            226,500,000
    //     0 -  60,000,000 @ 5%  =  3,000,000
    //    60m - 226,500,000 @ 15% = 24,975,000
    //   tax                       27,975,000
    const r = incomeTax(ID_2026, {
      grossIncome: '300000000',
      status: { married: true, dependants: 2 },
      deductionCodes: ['biaya_jabatan'],
    });
    expect(money(r.taxableIncome)).toBe(226_500_000);
    expect(money(r.taxPayable)).toBe(27_975_000);
    expect(r.slices).toHaveLength(2);
    expect(money(r.slices[0]!.taxInBand)).toBe(3_000_000);
    expect(money(r.slices[1]!.taxInBand)).toBe(24_975_000);
  });

  it('charges nothing below PTKP, and does not go negative', () => {
    const r = incomeTax(ID_2026, {
      grossIncome: '40000000',
      status: { married: false, dependants: 0 },
      deductionCodes: ['biaya_jabatan'],
    });
    expect(money(r.taxableIncome)).toBe(0);
    expect(money(r.taxPayable)).toBe(0);
    expect(r.slices).toEqual([]);
  });

  it('stamps the rules version onto the result', () => {
    // README principle 2: a figure that cannot be re-derived is not replayable.
    const r = incomeTax(ID_2026, {
      grossIncome: '120000000',
      status: { married: false, dependants: 0 },
    });
    expect(r.rulesId).toBe('id-2026');
    expect(r.rulesVersion).toBe(ID_2026.version);
    expect(r.taxYear).toBe('2026');
  });
});

describe('PP 23 — the finding that reshaped the engine', () => {
  it('is 0.5% of turnover above the first Rp 500m', () => {
    const r = alternativeRegime(ID_2026, 'pp23', { turnover: '1000000000' })!;
    expect(r.eligible).toBe(true);
    expect(money(r.taxPayable!)).toBe(2_500_000); // 0.5% of 500,000,000
  });

  it('charges nothing at or below the exempt turnover', () => {
    const r = alternativeRegime(ID_2026, 'pp23', { turnover: '500000000' })!;
    expect(money(r.taxPayable!)).toBe(0);
  });

  it('refuses above the Rp 4.8bn ceiling rather than computing a wrong figure', () => {
    const r = alternativeRegime(ID_2026, 'pp23', { turnover: '5000000000' })!;
    expect(r.eligible).toBe(false);
    expect(r.taxPayable).toBeNull();
    expect(r.ineligibleReason).toMatch(/ceiling/i);
  });

  it('states plainly that expenses have no effect, so the UI cannot imply otherwise', () => {
    // docs/INDONESIA.md §1. A tracker that keeps offering to categorise
    // deductions to a PP 23 taxpayer is lying by implication.
    const r = alternativeRegime(ID_2026, 'pp23', { turnover: '1000000000' })!;
    expect(r.deductionsAllowed).toBe(false);
    expect(r.note).toMatch(/FINAL tax on turnover/);
    expect(r.note).toMatch(/Expenses do not reduce it/);
  });
});

describe('NPPN', () => {
  it('refuses without the occupation percentage instead of inventing one', () => {
    // The rate varies by occupation and region (PER-17/PJ/2015) and no single
    // number could honestly live in the rule set.
    const r = alternativeRegime(ID_2026, 'nppn', { turnover: '600000000' })!;
    expect(r.eligible).toBe(false);
    expect(r.taxPayable).toBeNull();
  });

  it('deems net income and runs it through the ordinary scale', () => {
    // 600,000,000 turnover at a 50% norm = 300,000,000 deemed net.
    //   less PTKP TK/0  54,000,000 -> taxable 246,000,000
    //     0 - 60,000,000 @ 5%  =  3,000,000
    //    60m - 246,000,000 @ 15% = 27,900,000
    //   tax                       30,900,000
    const r = alternativeRegime(ID_2026, 'nppn', {
      turnover: '600000000',
      deemedProfitPercent: 50,
      status: { married: false, dependants: 0 },
    })!;
    expect(r.eligible).toBe(true);
    expect(money(r.taxPayable!)).toBe(30_900_000);
    expect(r.note).toMatch(/End of March/);
  });
});

describe('the PPN spending analytic', () => {
  it('reports what was paid and refuses to call it a claim', () => {
    const r = consumptionTaxPaid(ID_2026, [
      { inclusiveAmount: '1110000' },
      { inclusiveAmount: '50000', exempt: true }, // beras, PP 49/2022
      { inclusiveAmount: '220000', otherTaxAmount: '20000' }, // a meal, with PB1
    ]);
    expect(money(r.grossSpend)).toBe(1_380_000);
    expect(money(r.exemptSpend)).toBe(50_000);
    // 11/111 of the taxable 1,330,000
    expect(money(r.taxPaid)).toBe(131_802);
    expect(money(r.otherTaxPaid)).toBe(20_000);
    expect(r.recoverable).toBe(false);
    expect(r.disclosure).toMatch(/not a claim/);
    expect(r.disclosure).toMatch(/cannot be recovered/);
  });
});

describe('NPWP — saying what was not checked', () => {
  it('accepts 16 digits but does not claim to have validated them', () => {
    // docs/INDONESIA.md §3.2: an individual's NPWP is their NIK, which carries
    // no checksum. Reporting this as "valid" would imply a check never done.
    const r = checkTaxId(ID_2026, '3171234567890002');
    expect(r.ok).toBe(true);
    expect(r.confidence).toBe('length_only');
    expect(r.message).toMatch(/no checksum/i);
  });

  it('rejects a wrong digit count', () => {
    const r = checkTaxId(ID_2026, '12345');
    expect(r.ok).toBe(false);
    expect(r.message).toMatch(/16 or 15 digits/);
  });

  it('reports a missing NPWP rather than passing it', () => {
    expect(checkTaxId(ID_2026, null).ok).toBe(false);
    expect(checkTaxId(ID_2026, '').ok).toBe(false);
  });
});

describe('periods and dates', () => {
  it('groups by tax year, because a personal taxpayer files no PPN return', () => {
    expect(periodOf(ID_2026, '2026-03-14')).toBe('2026');
    expect(periodOf(ID_2026, '2026-11-02')).toBe('2026');
  });

  it('allows a document older than Australia would, because retention is 10 years', () => {
    // An 8-year-old Indonesian record is one the taxpayer is still legally
    // required to hold. validators.ts would refuse it at 7 years.
    expect(datePlausible(ID_2026, '2018-06-01', '2026-09-17').ok).toBe(true);
    expect(datePlausible(ID_2026, '2013-06-01', '2026-09-17').ok).toBe(false);
  });

  it('refuses a future date', () => {
    const r = datePlausible(ID_2026, '2027-01-01', '2026-09-17');
    expect(r.ok).toBe(false);
    expect(r.reason).toMatch(/future/);
  });
});

describe('reading rupiah off paper — the thousand-fold bug', () => {
  it('reads 15.000 as fifteen thousand, not fifteen', () => {
    // docs/INDONESIA.md §7.1. The existing money parser accepts "15.000" as
    // 15.0000 silently, and every downstream check passes because the tax
    // arithmetic stays internally consistent whatever the magnitude.
    expect(money(parseLocalAmount('15.000', IDR))).toBe(15_000);
    expect(money(parseLocalAmount('Rp 1.234.567', IDR))).toBe(1_234_567);
    expect(money(parseLocalAmount('Rp15.000', IDR))).toBe(15_000);
  });

  it('refuses a rupiah amount with a decimal part instead of coercing it', () => {
    // Rp 15,50 is not a price. It is a misread of a different convention, and
    // guessing which one is how the original bug happened.
    expect(() => parseLocalAmount('15,50', IDR)).toThrow(/no sub-unit/);
    expect(() => parseLocalAmount('15.0', IDR)).toThrow(/not a IDR amount/);
  });

  it('refuses a number that fits neither convention', () => {
    expect(() => parseLocalAmount('1,234,567.89', IDR)).toThrow();
    expect(() => parseLocalAmount('abc', IDR)).toThrow();
  });

  it('reads the same digits differently under a different currency', () => {
    // The point of putting separators in the rule set: "15.000" is fifteen
    // thousand rupiah and fifteen dollars, and only the rule set knows which.
    const AUD: CurrencySpec = {
      code: 'AUD',
      symbol: '$',
      locale: 'en-AU',
      minorUnits: 2,
      thousandsSeparator: ',',
      decimalSeparator: '.',
      tillRounding: 1,
    };
    expect(money(parseLocalAmount('15.00', AUD))).toBe(15);
    expect(money(parseLocalAmount('15.000', IDR))).toBe(15_000);
  });

  it('prints rupiah with no decimal part', () => {
    expect(formatLocalAmount('1110000', IDR)).toMatch(/^Rp\s?1\.110\.000$/);
  });
});
