"""Generate the tier-S corpus: images plus a manifest whose truth is built, not labelled.

`docs/CORPUS.md` §5, ticket X3.

    python -m factory.generate --count 300 --seed 20260916

Writes:
    corpus/generated/<doc-id>.png          the images
    corpus/generated/manifest.json         the manifest, in the committed shape

WHAT IS COMMITTED, AND WHY. The **manifest** is committed; the **images are
not** (they are gitignored and regenerated on demand). That is deliberate and
it is safe for a reason specific to this design: the truth is chosen before
rendering, so it does not depend on the renderer being byte-identical across
Chromium versions or platforms. A re-render that shifts a pixel does not make
the manifest wrong — the document still contains the values the manifest
claims. A hand-labelled corpus could not survive that, which is one more
argument for §5.2's rule.

Run it, then point the bench at it:
    python compare.py --manifest corpus/generated/manifest.json --dry-run
"""
from __future__ import annotations

import argparse
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from factory import degrade as deg  # noqa: E402
from factory import documents as D  # noqa: E402
from factory import render as R  # noqa: E402

BENCH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(BENCH, 'corpus', 'generated')

# How the corpus is composed. Weighted toward the cases that carry the product's
# claims rather than uniformly across archetypes:
#   supermarket  — THE WEDGE. Mixed GST/GST-free, which nobody else can split.
#   trade_invoice— the most commercially valuable class, and the long/multi-page one.
#   no_abn_van   — abstention. Over-represented on purpose: §8.3's coverage-risk
#                  curve needs documents where the right answer is "nothing here",
#                  and nobody ever collects enough of them.
ARCHETYPE_WEIGHTS = {
    'supermarket': 26,
    'fuel': 18,
    'hardware': 14,
    'cafe': 10,
    'trade_invoice': 18,
    'telco': 6,
    'no_abn_van': 8,
}

# Degradation mix. `clean` stays a minority: an upper bound is worth having and
# is not worth a third of the corpus.
DEGRADATION_WEIGHTS = {'clean': 20, 'light': 30, 'moderate': 30, 'severe': 20}


def _weighted(rng: random.Random, weights: dict[str, int]) -> str:
    return rng.choices(list(weights), weights=list(weights.values()), k=1)[0]


def _page_path(final_path: str) -> str:
    """How the manifest names an image: relative to bench/ when it lives there.

    `compare.py` resolves `pages` with `os.path.join(HERE, p)`, so a path
    relative to bench/ is what it expects. An `--out-dir` OUTSIDE the bench tree
    (a scratch directory during development) produced
    `../../../../../../AppData/...` from a naive relpath — technically valid,
    unreadable, and broken the moment the manifest moves. Fall back to the
    absolute path in that case, which `os.path.join` leaves intact.
    """
    rel = os.path.relpath(final_path, BENCH)
    if rel.startswith(os.pardir):
        return os.path.abspath(final_path).replace(os.sep, '/')
    return rel.replace(os.sep, '/')


def generate(count: int, seed: int, out_dir: str = OUT_DIR, scale: int = 2) -> dict:
    rng = random.Random(seed)
    os.makedirs(out_dir, exist_ok=True)

    docs, jobs, plan = [], [], []
    for i in range(count):
        archetype = _weighted(rng, ARCHETYPE_WEIGHTS)
        level = _weighted(rng, DEGRADATION_WEIGHTS)
        doc = D.build(rng, archetype, i)
        raw_path = os.path.join(out_dir, f'{doc.doc_id}.raw.png')
        final_path = os.path.join(out_dir, f'{doc.doc_id}.png')
        docs.append(doc)
        jobs.append((doc, rng.uniform(-3.4, 3.4), raw_path))
        plan.append((doc, level, raw_path, final_path, rng.randrange(2**31)))

    print(f'rendering {len(jobs)} documents...', flush=True)
    R.render_many(jobs, scale=scale)

    print('degrading...', flush=True)
    from PIL import Image

    entries = []
    for doc, level, raw_path, final_path, dseed in plan:
        with Image.open(raw_path) as img:
            out = deg.apply(img, level, random.Random(dseed))
            out.save(final_path)
        os.remove(raw_path)
        entries.append(D.manifest_entry(doc, [_page_path(final_path)], 'image', level))

    manifest = {
        '_comment': (
            'GENERATED by factory/generate.py — do not hand-edit. Ground truth is chosen by the '
            'generator BEFORE rendering and the renderer prints exactly those values, so no '
            'document here was ever labelled by reading an image (docs/CORPUS.md §5.2). Every '
            'document is tier S: faithful for structure, abstention and grounding; OPTIMISTIC '
            'for recall and CER; unusable for calibration. provenance.py enforces that.'
        ),
        'generator': {'seed': seed, 'count': count, 'module': 'factory.generate'},
        'prompt_version': 'v1',
        'documents': entries,
    }
    manifest_path = os.path.join(out_dir, 'manifest.json')
    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
        f.write('\n')

    return {'manifest_path': manifest_path, 'manifest': manifest, 'docs': docs}


def summarise(manifest: dict) -> str:
    docs = manifest['documents']
    by_arch: dict[str, int] = {}
    by_deg: dict[str, int] = {}
    mixed = sum(1 for d in docs if d.get('mixed_tax'))
    abstain = sum(1 for d in docs if d['fields']['supplier_abn']['truth'] is None)
    ambiguous = sum(1 for d in docs if d.get('date_is_ambiguous'))
    lines = sum(d['fields']['line_count']['truth'] for d in docs)
    for d in docs:
        by_arch[d['archetype']] = by_arch.get(d['archetype'], 0) + 1
        by_deg[d['degradation']] = by_deg.get(d['degradation'], 0) + 1
    return '\n'.join([
        f'documents:      {len(docs)}',
        f'line items:     {lines}',
        f'by archetype:   {dict(sorted(by_arch.items()))}',
        f'by degradation: {dict(sorted(by_deg.items()))}',
        f'mixed GST/GST-free (the wedge): {mixed}',
        f'abstention (no ABN printed):    {abstain}',
        f'ambiguous dates (day <= 12):    {ambiguous}',
    ])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--count', type=int, default=300)
    ap.add_argument('--seed', type=int, default=20260916)
    ap.add_argument('--out-dir', default=OUT_DIR)
    ap.add_argument('--scale', type=int, default=2, help='device scale factor for rendering')
    args = ap.parse_args()

    result = generate(args.count, args.seed, args.out_dir, args.scale)

    # Validate what we just wrote with the SAME controls the harness applies,
    # rather than trusting the generator. A corpus that cannot pass the gate is
    # not a corpus, and finding that out here beats finding it out mid-run.
    import abn as abn_mod
    import provenance as prov

    abn_mod.assert_manifest_abns_valid(result['manifest'])
    prov.assert_manifest_provenance_valid(result['manifest'])

    print()
    print(summarise(result['manifest']))
    print()
    print(f"wrote {result['manifest_path']}")
    print(prov.banner(prov.weakest_tier(result['manifest']['documents'])))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
