-- 0001_extensions_domains_enums
-- Extensions, money domains, enums, helper functions
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid, digest
CREATE EXTENSION IF NOT EXISTS pg_trgm;    -- fuzzy supplier-name matching
CREATE EXTENSION IF NOT EXISTS btree_gin;
CREATE EXTENSION IF NOT EXISTS citext;     -- case-insensitive email

-- -----------------------------------------------------------------------------
-- 1. Domains — money is NUMERIC, never float, and currency always sits beside it
-- -----------------------------------------------------------------------------
CREATE DOMAIN money_amount  AS NUMERIC(19,4);  -- totals, tax amounts, split amounts
CREATE DOMAIN unit_price    AS NUMERIC(19,6);  -- fuel at $1.899/L, produce per kg
CREATE DOMAIN quantity      AS NUMERIC(19,6);
CREATE DOMAIN tax_rate      AS NUMERIC(6,4);   -- 10.0000
CREATE DOMAIN currency_code AS CHAR(3)
  CONSTRAINT currency_code_iso4217 CHECK (VALUE ~ '^[A-Z]{3}$');
CREATE DOMAIN confidence    AS NUMERIC(4,3)
  CONSTRAINT confidence_range CHECK (VALUE >= 0 AND VALUE <= 1);
CREATE DOMAIN country_code  AS CHAR(2)
  CONSTRAINT country_code_iso3166 CHECK (VALUE ~ '^[A-Z]{2}$');

-- -----------------------------------------------------------------------------
-- 2. Enums
-- -----------------------------------------------------------------------------
CREATE TYPE capture_status    AS ENUM ('received','processing','extracted','failed','quarantined');
CREATE TYPE doc_type          AS ENUM ('tax_invoice','invoice','receipt','credit_note','statement','unknown');
CREATE TYPE review_status     AS ENUM ('auto_accepted','needs_review','reviewed','rejected');
CREATE TYPE extraction_engine AS ENUM ('claude_vision','claude_text','ocr_llm','manual','import');
CREATE TYPE run_status        AS ENUM ('queued','running','succeeded','failed','superseded');
CREATE TYPE account_type      AS ENUM ('asset','liability','equity','income','expense');
CREATE TYPE txn_status        AS ENUM ('draft','posted','void');
CREATE TYPE txn_source        AS ENUM ('scan','manual','import','bank_feed','recurring');
CREATE TYPE gst_basis         AS ENUM ('cash','accrual');

-- -----------------------------------------------------------------------------
-- 3. Helper functions
-- -----------------------------------------------------------------------------

-- ABN checksum (ABR modulus-89). Subtract 1 from the first digit, apply weights,
-- sum, and the total must divide evenly by 89. IMMUTABLE so it can back a
-- generated column.
CREATE OR REPLACE FUNCTION abn_is_valid(p_abn text)
RETURNS boolean LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
DECLARE
  w int[] := ARRAY[10,1,3,5,7,9,11,13,15,17,19];
  d text;
  s int := 0;
  i int;
BEGIN
  IF p_abn IS NULL THEN RETURN NULL; END IF;
  d := regexp_replace(p_abn, '[^0-9]', '', 'g');
  IF length(d) <> 11 THEN RETURN false; END IF;
  s := (substr(d,1,1)::int - 1) * w[1];
  FOR i IN 2..11 LOOP
    s := s + substr(d,i,1)::int * w[i];
  END LOOP;
  RETURN s % 89 = 0;
END $$;

CREATE OR REPLACE FUNCTION current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid
$$;
