-- 0002_tenancy
-- Tenants, users, memberships, API clients
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

-- -----------------------------------------------------------------------------
-- 4. Tenancy & identity
-- -----------------------------------------------------------------------------
CREATE TABLE tenants (
  id              uuid PRIMARY KEY,
  name            text NOT NULL,
  abn             char(11),
  abn_valid       boolean GENERATED ALWAYS AS (abn_is_valid(abn)) STORED,
  gst_registered  boolean NOT NULL DEFAULT false,
  gst_basis       gst_basis NOT NULL DEFAULT 'cash',
  simpler_bas     boolean NOT NULL DEFAULT true,   -- < $10M turnover: G1, 1A, 1B only
  country         country_code NOT NULL DEFAULT 'AU',
  base_currency   currency_code NOT NULL DEFAULT 'AUD',
  financial_year_start_month smallint NOT NULL DEFAULT 7,  -- AU FY starts July
  -- Drives profile-aware categorisation: which deduction labels this taxpayer can claim.
  -- Values are @snap/tax-engine profile ids: 'truckie_long', 'tradie', 'nurse', 'sole', ...
  occupation_profile_id text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  deleted_at      timestamptz
);

CREATE TABLE users (
  id          uuid PRIMARY KEY,
  subject     text NOT NULL UNIQUE,   -- external IdP subject; we never store passwords
  email       citext,
  display_name text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE memberships (
  tenant_id  uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  role       text NOT NULL CHECK (role IN ('owner','admin','bookkeeper','member','readonly')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, user_id)
);

CREATE TABLE api_clients (
  id          uuid PRIMARY KEY,
  tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name        text NOT NULL,
  key_prefix  text NOT NULL,          -- searchable, non-secret
  key_hash    bytea NOT NULL,         -- argon2id of the full key
  scopes      text[] NOT NULL DEFAULT '{}',
  last_used_at timestamptz,
  revoked_at  timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (key_prefix)
);
