-- 0003_capture_extraction
-- Immutable captures and versioned extraction runs
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

-- -----------------------------------------------------------------------------
-- 5. Capture layer — IMMUTABLE. The original is the legal record.
--
-- The ATO accepts electronic copies only where they are a "true and clear
-- reproduction" of the original. original_storage_key is written once and never
-- modified; normalised_storage_key holds the derivative we send to the model.
-- -----------------------------------------------------------------------------
CREATE TABLE captures (
  id                     uuid PRIMARY KEY,
  tenant_id              uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  uploaded_by            uuid REFERENCES users(id),

  original_storage_key   text NOT NULL,
  original_mime_type     text NOT NULL,
  original_byte_size     bigint NOT NULL CHECK (original_byte_size > 0),
  original_sha256        bytea NOT NULL,
  normalised_storage_key text,        -- derivative: deskewed, EXIF-stripped, <=1568px

  phash                  bigint,      -- perceptual hash for near-duplicate detection
  page_count             int NOT NULL DEFAULT 1,

  captured_at            timestamptz, -- device clock
  received_at            timestamptz NOT NULL DEFAULT now(),

  device_meta            jsonb NOT NULL DEFAULT '{}',
  legibility_score       confidence,  -- pre-flight quality gate result

  status                 capture_status NOT NULL DEFAULT 'received',
  retention_until        date,        -- mirrors the document; originals are undeletable before this

  -- Exact re-upload of the same bytes is idempotent, not an error.
  CONSTRAINT captures_sha_unique UNIQUE (tenant_id, original_sha256)
);
CREATE INDEX captures_tenant_received_idx ON captures (tenant_id, received_at DESC);
CREATE INDEX captures_phash_idx           ON captures (tenant_id, phash) WHERE phash IS NOT NULL;
CREATE INDEX captures_status_idx          ON captures (status) WHERE status <> 'extracted';

-- -----------------------------------------------------------------------------
-- 6. Extraction layer — versioned and replayable
-- -----------------------------------------------------------------------------
CREATE TABLE extraction_runs (
  id             uuid PRIMARY KEY,
  tenant_id      uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  capture_id     uuid NOT NULL REFERENCES captures(id) ON DELETE CASCADE,

  engine         extraction_engine NOT NULL,
  model_id       text,                -- e.g. 'claude-haiku-4-5'
  prompt_version text NOT NULL,
  schema_version text NOT NULL,
  tier           smallint NOT NULL DEFAULT 1,

  status         run_status NOT NULL DEFAULT 'queued',
  error          text,

  started_at     timestamptz,
  finished_at    timestamptz,
  latency_ms     int,

  -- Per-scan cost accounting. Without this you cannot answer "what does a scan cost".
  input_tokens   int,
  output_tokens  int,
  cached_tokens  int,
  cost_micros    bigint,

  raw_response   jsonb,               -- exact model output, for audit and replay
  validator_report jsonb,             -- which deterministic checks passed/failed

  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX extraction_runs_capture_idx ON extraction_runs (capture_id, created_at DESC);
CREATE INDEX extraction_runs_cost_idx    ON extraction_runs (tenant_id, created_at DESC);
