-- 0004_parties_documents
-- Party master, documents, lines, tax subtotals
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

-- -----------------------------------------------------------------------------
-- 7. Parties (supplier / buyer master)
-- -----------------------------------------------------------------------------
CREATE TABLE parties (
  id               uuid PRIMARY KEY,
  tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  legal_name       text NOT NULL,          -- BT-27 / BT-44
  trading_name     text,                   -- BT-28 / BT-45
  name_normalised  text NOT NULL,          -- lowercased, punctuation-stripped, for matching

  abn              char(11),
  abn_valid        boolean GENERATED ALWAYS AS (abn_is_valid(abn)) STORED,
  abn_verified_at  timestamptz,            -- set only after an ABR Lookup call
  abn_status       text,                   -- 'Active' / 'Cancelled' from ABR
  gst_registered   boolean,                -- from ABR; affects credit eligibility
  acn              char(9),

  address_line1    text,                   -- BG-5 / BG-8
  address_line2    text,
  city             text,
  state            text,
  postcode         text,
  country          country_code NOT NULL DEFAULT 'AU',

  email            text,
  phone            text,

  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX parties_abn_idx  ON parties (tenant_id, abn) WHERE abn IS NOT NULL;
CREATE INDEX parties_name_trgm ON parties USING gin (name_normalised gin_trgm_ops);

-- -----------------------------------------------------------------------------
-- 8. Document layer — curated, one current per capture, Peppol-shaped
-- -----------------------------------------------------------------------------
CREATE TABLE documents (
  id                    uuid PRIMARY KEY,
  tenant_id             uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  capture_id            uuid NOT NULL REFERENCES captures(id) ON DELETE CASCADE,
  current_run_id        uuid REFERENCES extraction_runs(id),

  -- Internal classification vs Peppol code vs ATO validity: three different things.
  -- In AU a supermarket receipt often IS a tax invoice; Peppol has no "receipt".
  doc_type              doc_type NOT NULL DEFAULT 'unknown',
  document_type_code    text,          -- BT-3, UNCL1001 (380 invoice, 381 credit note); NULL when not Peppol-exportable
  is_tax_invoice        boolean NOT NULL DEFAULT false,  -- set by validators; GATES GST CREDIT CLAIMS
  ato_compliance        jsonb NOT NULL DEFAULT '{}',     -- which of the 7 required elements were found

  document_number       text,          -- BT-1
  issue_date            date,          -- BT-2
  due_date              date,          -- BT-9
  currency              currency_code NOT NULL DEFAULT 'AUD',  -- BT-5

  supplier_id           uuid REFERENCES parties(id),
  buyer_id              uuid REFERENCES parties(id),

  line_extension_amount money_amount,  -- BT-106  sum of line net amounts
  tax_exclusive_amount  money_amount,  -- BT-109
  tax_amount            money_amount,  -- BT-110  total GST
  tax_inclusive_amount  money_amount,  -- BT-112
  rounding_amount       money_amount NOT NULL DEFAULT 0,  -- BT-114; AU cash rounds to 5c
  payable_amount        money_amount,  -- BT-115

  payment_method        text,
  card_last4            char(4),       -- masked PAN only. Never store a full PAN (PCI scope).
  card_brand            text,

  review_status         review_status NOT NULL DEFAULT 'needs_review',
  confidence_overall    confidence,
  field_provenance      jsonb NOT NULL DEFAULT '{}',  -- {"supplier.abn": {"conf":0.98,"bbox":[...]}}

  dedup_group_id        uuid,          -- business-key fingerprint group; flag, never auto-merge
  retention_until       date,          -- issue_date + 5 years (ATO)

  -- Human review (see section 15). locked_fields holds the field paths a person has
  -- confirmed or edited; a later re-extraction MUST NOT overwrite them.
  locked_fields         text[] NOT NULL DEFAULT '{}',
  reviewed_by           uuid REFERENCES users(id),
  reviewed_at           timestamptz,

  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  deleted_at            timestamptz,

  CONSTRAINT documents_capture_unique UNIQUE (capture_id)
);
CREATE INDEX documents_tenant_issue_idx ON documents (tenant_id, issue_date DESC);
CREATE INDEX documents_review_idx       ON documents (tenant_id, review_status) WHERE review_status = 'needs_review';
CREATE INDEX documents_supplier_idx     ON documents (tenant_id, supplier_id);
CREATE INDEX documents_dedup_idx        ON documents (tenant_id, dedup_group_id) WHERE dedup_group_id IS NOT NULL;
CREATE INDEX documents_provenance_idx   ON documents USING gin (field_provenance);
CREATE INDEX documents_retention_idx    ON documents (retention_until) WHERE deleted_at IS NULL;

CREATE TABLE document_lines (
  id               uuid PRIMARY KEY,
  tenant_id        uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  document_id      uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,

  line_number      int NOT NULL,       -- BT-126
  description      text,               -- BT-153
  item_code        text,               -- BT-155 seller's item identifier
  quantity         quantity,           -- BT-129
  unit_code        text,               -- BT-130, UN/ECE Rec 20: EA, LTR, KGM, HUR
  unit_price       unit_price,         -- BT-146
  line_net_amount  money_amount,       -- BT-131
  discount_amount  money_amount NOT NULL DEFAULT 0,

  gst_category_code text,              -- BT-151, UNCL5305: S standard, Z GST-free, E exempt, O out of scope
  gst_rate         tax_rate,           -- BT-152
  gst_amount       money_amount,

  category_id      uuid,               -- set by user/rules, FK added below
  line_confidence  confidence,

  UNIQUE (document_id, line_number)
);
CREATE INDEX document_lines_document_idx ON document_lines (document_id);

-- Peppol BG-23. A TABLE, not a column: a grocery receipt legitimately mixes
-- GST-free fresh food with taxable packaged goods, and one total cannot say that.
CREATE TABLE document_tax_subtotals (
  id              uuid PRIMARY KEY,
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  document_id     uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  category_code   text NOT NULL,       -- BT-118
  rate            tax_rate NOT NULL,   -- BT-119
  taxable_amount  money_amount NOT NULL,  -- BT-116
  tax_amount      money_amount NOT NULL,  -- BT-117
  UNIQUE (document_id, category_code, rate)
);

-- Sparse: only records human edits, so the review queue is queryable without EAV sprawl.
CREATE TABLE document_field_corrections (
  id            uuid PRIMARY KEY,
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  document_id   uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  field_path    text NOT NULL,        -- 'supplier.abn', 'lines[3].unit_price'
  old_value     text,
  new_value     text,
  from_run_id   uuid REFERENCES extraction_runs(id),
  corrected_by  uuid REFERENCES users(id),
  corrected_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dfc_document_idx ON document_field_corrections (document_id);
-- Every correction is training signal. Mine this table before touching the prompt.
CREATE INDEX dfc_field_idx    ON document_field_corrections (tenant_id, field_path);
