-- 0005_accounts_tax_codes
-- Chart of accounts, categories, AU tax codes
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

-- -----------------------------------------------------------------------------
-- 9. Chart of accounts, categories, tax codes
-- -----------------------------------------------------------------------------
CREATE TABLE accounts (
  id            uuid PRIMARY KEY,
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  code          text NOT NULL,         -- '6-1200'
  name          text NOT NULL,
  account_type  account_type NOT NULL,
  parent_id     uuid REFERENCES accounts(id),
  is_capital    boolean NOT NULL DEFAULT false,  -- capital assets drive BAS G10 vs G11
  external_refs jsonb NOT NULL DEFAULT '{}',     -- {"xero":"...","myob":"..."}
  is_archived   boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, code)
);

CREATE TABLE categories (
  id                  uuid PRIMARY KEY,
  tenant_id           uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name                text NOT NULL,
  parent_id           uuid REFERENCES categories(id),
  default_account_id  uuid REFERENCES accounts(id),
  default_tax_code_id uuid,                       -- FK added after tax_codes
  -- @snap/tax-engine target, not free text: 'D1.logbook.fuel', 'D3.laundry', 'D2.meals.dinner'.
  -- This is what lets a scan land in the exact worksheet row the engine expects.
  engine_row_id       text,
  ato_deduction_code  text,                       -- D1-D14 label
  UNIQUE (tenant_id, name)
);
ALTER TABLE document_lines
  ADD CONSTRAINT document_lines_category_fk
  FOREIGN KEY (category_id) REFERENCES categories(id);

-- Industry-standard tax codes, mirroring Xero/MYOB. Each declares its BAS labels,
-- which turns BAS reporting into a GROUP BY and export into a lookup.
CREATE TABLE tax_codes (
  id              uuid PRIMARY KEY,
  tenant_id       uuid REFERENCES tenants(id) ON DELETE CASCADE,  -- NULL = system-seeded
  code            text NOT NULL,
  name            text NOT NULL,
  rate            tax_rate NOT NULL,
  purchase_labels text[] NOT NULL DEFAULT '{}',   -- e.g. {G11,1B}
  sale_labels     text[] NOT NULL DEFAULT '{}',   -- e.g. {G1,1A}
  claims_credit   boolean NOT NULL DEFAULT false, -- true => needs a valid tax invoice to claim
  external_refs   jsonb NOT NULL DEFAULT '{}',
  UNIQUE (tenant_id, code)
);
ALTER TABLE categories
  ADD CONSTRAINT categories_tax_code_fk
  FOREIGN KEY (default_tax_code_id) REFERENCES tax_codes(id);

INSERT INTO tax_codes (id, tenant_id, code, name, rate, purchase_labels, sale_labels, claims_credit) VALUES
  (gen_random_uuid(), NULL, 'GST',         'GST on non-capital purchases', 10.0000, '{G11,1B}', '{}',      true),
  (gen_random_uuid(), NULL, 'CAP',         'GST on capital purchases',     10.0000, '{G10,1B}', '{}',      true),
  (gen_random_uuid(), NULL, 'GSTONINCOME', 'GST on sales',                 10.0000, '{}',       '{G1,1A}', false),
  (gen_random_uuid(), NULL, 'FRE',         'GST-free',                      0.0000, '{G11}',    '{G1}',    false),
  (gen_random_uuid(), NULL, 'INP',         'Input-taxed',                   0.0000, '{G11}',    '{G1}',    false),
  (gen_random_uuid(), NULL, 'EXP',         'Export sale',                   0.0000, '{}',       '{G1}',    false),
  (gen_random_uuid(), NULL, 'N-T',         'Not reportable',                0.0000, '{}',       '{}',      false);
