-- 0006_ledger
-- Double-entry ledger, sum-zero trigger, BAS view
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

-- -----------------------------------------------------------------------------
-- 10. The ledger — double-entry, provably balanced
--
-- Sign convention: DEBITS POSITIVE, CREDITS NEGATIVE.
-- Assets and expenses increase positive; liabilities, equity and income
-- increase negative. Splits of a posted transaction must sum to exactly zero.
-- -----------------------------------------------------------------------------
CREATE TABLE transactions (
  id             uuid PRIMARY KEY,
  tenant_id      uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  txn_date       date NOT NULL,
  settled_date   date,                 -- cash-basis GST filters on this
  payee_id       uuid REFERENCES parties(id),
  memo           text,
  reference      text,
  currency       currency_code NOT NULL DEFAULT 'AUD',

  status         txn_status NOT NULL DEFAULT 'draft',
  source         txn_source NOT NULL DEFAULT 'manual',
  document_id    uuid REFERENCES documents(id),   -- evidence; kept for the record's life

  posted_at      timestamptz,
  posted_by      uuid REFERENCES users(id),
  voided_at      timestamptz,
  void_reason    text,

  external_refs  jsonb NOT NULL DEFAULT '{}',     -- {"xero":{"id":"...","synced_at":"..."}}

  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT txn_posted_has_timestamp CHECK (status <> 'posted' OR posted_at IS NOT NULL)
);
CREATE INDEX transactions_tenant_date_idx ON transactions (tenant_id, txn_date DESC);
CREATE INDEX transactions_document_idx    ON transactions (document_id) WHERE document_id IS NOT NULL;
CREATE INDEX transactions_status_idx      ON transactions (tenant_id, status);

CREATE TABLE transaction_splits (
  id             uuid PRIMARY KEY,
  tenant_id      uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  transaction_id uuid NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  line_number    int NOT NULL,

  account_id     uuid NOT NULL REFERENCES accounts(id),
  amount         money_amount NOT NULL,     -- signed; debit +, credit -

  -- tax_code_id NOT NULL  => this is a BAS-reportable line and gst_amount is its GST.
  -- tax_code_id IS NULL   => this is the GST control-account posting (or a transfer leg);
  --                          excluded from BAS aggregation so GST is never double-counted.
  tax_code_id    uuid REFERENCES tax_codes(id),
  gst_amount     money_amount NOT NULL DEFAULT 0,

  category_id    uuid REFERENCES categories(id),
  document_line_id uuid REFERENCES document_lines(id),
  description    text,

  UNIQUE (transaction_id, line_number),
  CONSTRAINT split_gst_needs_tax_code CHECK (gst_amount = 0 OR tax_code_id IS NOT NULL)
);
CREATE INDEX splits_txn_idx     ON transaction_splits (transaction_id);
CREATE INDEX splits_account_idx ON transaction_splits (tenant_id, account_id);
CREATE INDEX splits_taxcode_idx ON transaction_splits (tenant_id, tax_code_id) WHERE tax_code_id IS NOT NULL;

-- The invariant, enforced by the database rather than by application discipline.
-- DEFERRABLE INITIALLY DEFERRED => checked once at COMMIT, so a client can insert
-- the header and all splits in any order. Drafts and voids are exempt, which is
-- what lets half-built entries be edited and deleted freely.
CREATE OR REPLACE FUNCTION assert_transaction_balanced() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_txn    uuid;
  v_status txn_status;
  v_sum    money_amount;
BEGIN
  IF TG_TABLE_NAME = 'transactions' THEN
    v_txn := COALESCE(NEW.id, OLD.id);
  ELSE
    v_txn := COALESCE(NEW.transaction_id, OLD.transaction_id);
  END IF;

  SELECT status INTO v_status FROM transactions WHERE id = v_txn;
  IF v_status IS DISTINCT FROM 'posted' THEN
    RETURN NULL;                       -- drafts and voids need not balance
  END IF;

  SELECT COALESCE(SUM(amount), 0) INTO v_sum
  FROM transaction_splits WHERE transaction_id = v_txn;

  IF v_sum <> 0 THEN
    RAISE EXCEPTION 'transaction % is not balanced: splits sum to %', v_txn, v_sum
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER trg_splits_balanced
  AFTER INSERT OR UPDATE OR DELETE ON transaction_splits
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION assert_transaction_balanced();

CREATE CONSTRAINT TRIGGER trg_txn_balanced_on_post
  AFTER INSERT OR UPDATE OF status ON transactions
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION assert_transaction_balanced();

-- -----------------------------------------------------------------------------
-- 11. BAS reporting
--
-- G1  total sales incl GST         1A GST on sales
-- G10 capital purchases incl GST   1B GST on purchases (credit-claimable only)
-- G11 non-capital purchases incl GST
--
-- Simpler BAS (turnover < $10M) reports only G1, 1A, 1B.
-- 1A ~= G1/11 and 1B ~= (G10+G11)/11 are shipped as sanity checks on the report.
--
-- THE CRITICAL RULE: a GST input credit may only be claimed where a valid tax
-- invoice is held. So a credit-claiming split contributes to 1B only when its
-- evidence document has is_tax_invoice = true. Everything else becomes the
-- "unclaimable GST" figure the app surfaces to the user.
-- -----------------------------------------------------------------------------
CREATE VIEW v_bas_lines AS
SELECT
  t.tenant_id,
  t.id                                   AS transaction_id,
  COALESCE(t.settled_date, t.txn_date)   AS cash_date,
  t.txn_date                             AS accrual_date,
  s.id                                   AS split_id,
  tc.code                                AS tax_code,
  tc.purchase_labels,
  tc.sale_labels,
  tc.claims_credit,
  abs(s.amount)                          AS net_amount,
  s.gst_amount,
  abs(s.amount) + s.gst_amount           AS gross_amount,
  COALESCE(d.is_tax_invoice, false)      AS has_valid_tax_invoice,
  (tc.claims_credit AND NOT COALESCE(d.is_tax_invoice, false)) AS gst_unclaimable
FROM transaction_splits s
JOIN transactions t  ON t.id = s.transaction_id
JOIN tax_codes    tc ON tc.id = s.tax_code_id      -- NULL tax_code => not reportable
LEFT JOIN documents d ON d.id = t.document_id
WHERE t.status = 'posted';
