-- 0007_ops
-- Review queue, audit log, jobs, webhooks
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

-- -----------------------------------------------------------------------------
-- 12. Operations: review queue, audit, jobs, idempotency, webhooks
-- -----------------------------------------------------------------------------
CREATE TABLE review_tasks (
  id          uuid PRIMARY KEY,
  tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  document_id uuid REFERENCES documents(id) ON DELETE CASCADE,
  transaction_id uuid REFERENCES transactions(id) ON DELETE CASCADE,
  reason      text NOT NULL,          -- 'gst_arithmetic_failed', 'abn_invalid', 'possible_duplicate'
  detail      jsonb NOT NULL DEFAULT '{}',
  priority    smallint NOT NULL DEFAULT 5,
  resolved_at timestamptz,
  resolved_by uuid REFERENCES users(id),
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX review_open_idx ON review_tasks (tenant_id, priority) WHERE resolved_at IS NULL;

-- Append-only. INSERT granted; UPDATE and DELETE granted to nobody.
-- This is what makes scoping a notifiable breach possible at all.
CREATE TABLE audit_log (
  id          bigserial PRIMARY KEY,
  tenant_id   uuid,
  actor_type  text NOT NULL,          -- 'user','api_client','system'
  actor_id    uuid,
  action      text NOT NULL,          -- 'document.corrected','transaction.posted','export.xero'
  entity_type text NOT NULL,
  entity_id   uuid,
  before      jsonb,
  after       jsonb,
  request_id  text,
  ip          inet,
  at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_tenant_at_idx ON audit_log (tenant_id, at DESC);
CREATE INDEX audit_entity_idx    ON audit_log (entity_type, entity_id);

CREATE TABLE jobs (
  id           uuid PRIMARY KEY,
  tenant_id    uuid REFERENCES tenants(id) ON DELETE CASCADE,
  kind         text NOT NULL,         -- 'extract','xero_push','purge','export_pack'
  payload      jsonb NOT NULL DEFAULT '{}',
  run_after    timestamptz NOT NULL DEFAULT now(),
  attempts     int NOT NULL DEFAULT 0,
  max_attempts int NOT NULL DEFAULT 5,
  locked_at    timestamptz,
  locked_by    text,
  last_error   text,
  completed_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);
-- Worker: SELECT ... WHERE completed_at IS NULL AND run_after <= now()
--         ORDER BY run_after FOR UPDATE SKIP LOCKED LIMIT n
CREATE INDEX jobs_ready_idx ON jobs (kind, run_after) WHERE completed_at IS NULL;

CREATE TABLE idempotency_keys (
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  key           text NOT NULL,
  request_hash  bytea NOT NULL,
  response_code int,
  response_body jsonb,
  created_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, key)
);

CREATE TABLE webhook_endpoints (
  id          uuid PRIMARY KEY,
  tenant_id   uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  url         text NOT NULL,
  secret      bytea NOT NULL,        -- HMAC signing key, encrypted at rest
  events      text[] NOT NULL DEFAULT '{}',
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE webhook_deliveries (
  id           uuid PRIMARY KEY,
  endpoint_id  uuid NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE,
  event        text NOT NULL,
  payload      jsonb NOT NULL,
  attempts     int NOT NULL DEFAULT 0,
  status_code  int,
  delivered_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- External accounting connections. Xero limits: 60 calls/min, 5,000/day,
-- 5 concurrent per second, PER TENANT TOKEN. Push must go through a queue.
CREATE TABLE accounting_connections (
  id                uuid PRIMARY KEY,
  tenant_id         uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  provider          text NOT NULL CHECK (provider IN ('xero','myob','quickbooks')),
  external_tenant_id text NOT NULL,
  access_token      bytea NOT NULL,   -- AEAD ciphertext, KMS-wrapped DEK
  refresh_token     bytea NOT NULL,
  expires_at        timestamptz,
  scopes            text[] NOT NULL DEFAULT '{}',
  connected_by      uuid REFERENCES users(id),
  revoked_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, provider, external_tenant_id)
);
