-- 0008_billing_usage
-- Plans, subscriptions, quota metering
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

-- -----------------------------------------------------------------------------
-- 14. Plans, subscriptions & usage metering
--
-- AI cost scales with SCANS, not users, so scans are what gets metered. Quota is
-- tenant-level with seats as a separate limit (the shape Dext uses: 250 docs / 5 users).
--
-- Two rules encoded here:
--   * Soft cap, not a wall. At quota, offer a top-up (usage_grants) rather than
--     refusing the scan.
--   * NEVER drop a capture. If quota is gone and the user declines a top-up, the
--     image is still stored and extraction runs later. Losing a receipt is
--     unforgivable in a product whose promise is not losing receipts.
-- -----------------------------------------------------------------------------
CREATE TYPE sub_status       AS ENUM ('trialing','active','past_due','canceled','paused');
CREATE TYPE billing_provider AS ENUM ('stripe','apple','google','manual');

CREATE TABLE plans (
  id               uuid PRIMARY KEY,
  code             text NOT NULL UNIQUE,           -- 'free','sorted','pro'
  name             text NOT NULL,
  price_cents      int NOT NULL,                   -- AUD, GST-INCLUSIVE (consumer convention)
  currency         currency_code NOT NULL DEFAULT 'AUD',
  scan_quota       int,                            -- per billing period; NULL = unmetered
  seat_limit       int NOT NULL DEFAULT 1,
  realtime         boolean NOT NULL DEFAULT true,  -- false => batch tier: slower, never less accurate
  retention_months int NOT NULL DEFAULT 60,        -- ATO minimum is 5 years = 60
  features         jsonb NOT NULL DEFAULT '{}',
  is_active        boolean NOT NULL DEFAULT true,
  CONSTRAINT plans_price_nonneg CHECK (price_cents >= 0)
);

INSERT INTO plans (id, code, name, price_cents, scan_quota, seat_limit, realtime, retention_months, features) VALUES
  (gen_random_uuid(),'free',  'Free',     0,  20,  1, false, 12,
     '{"xero":false,"api":false,"tax_pack":false,"ledger":"read_only"}'),
  (gen_random_uuid(),'sorted','Sorted', 999, 150,  3, true,  60,
     '{"xero":true,"api":false,"tax_pack":true,"ledger":"full"}'),
  (gen_random_uuid(),'pro',   'Pro',   2499, 600, 10, true,  84,
     '{"xero":true,"myob":true,"quickbooks":true,"api":true,"tax_pack":true,"ledger":"full","multi_entity":true}');

CREATE TABLE subscriptions (
  id                   uuid PRIMARY KEY,
  tenant_id            uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  plan_id              uuid NOT NULL REFERENCES plans(id),
  status               sub_status NOT NULL DEFAULT 'trialing',
  provider             billing_provider NOT NULL,
  external_id          text,  -- Stripe sub id / Apple original_transaction_id / Play purchaseToken
  current_period_start timestamptz NOT NULL,
  current_period_end   timestamptz NOT NULL,
  cancel_at            timestamptz,
  canceled_at          timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sub_period_ordered CHECK (current_period_end > current_period_start)
);
-- At most one live subscription per tenant.
CREATE UNIQUE INDEX subscriptions_one_live_idx ON subscriptions (tenant_id)
  WHERE status IN ('trialing','active','past_due');
CREATE UNIQUE INDEX subscriptions_external_idx ON subscriptions (provider, external_id)
  WHERE external_id IS NOT NULL;

-- Fast pre-flight counter. extraction_runs stays the source of truth, so this is
-- always rebuildable from it and never authoritative on its own.
CREATE TABLE usage_counters (
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  period_start date NOT NULL,
  metric       text NOT NULL,                      -- 'scans'
  used         int  NOT NULL DEFAULT 0,
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, period_start, metric),
  CONSTRAINT usage_used_nonneg CHECK (used >= 0)
);

-- Top-up packs and goodwill credits. Consumed only after the plan quota.
CREATE TABLE usage_grants (
  id         uuid PRIMARY KEY,
  tenant_id  uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  metric     text NOT NULL DEFAULT 'scans',
  amount     int  NOT NULL CHECK (amount > 0),
  remaining  int  NOT NULL CHECK (remaining >= 0),
  source     text NOT NULL,                        -- 'topup_pack','referral','support_credit'
  granted_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  CONSTRAINT grant_remaining_le_amount CHECK (remaining <= amount)
);
CREATE INDEX usage_grants_live_idx ON usage_grants (tenant_id, metric) WHERE remaining > 0;

-- The single place the API asks: may this tenant scan right now, and how fast?
CREATE VIEW v_tenant_entitlement AS
SELECT
  t.id                   AS tenant_id,
  p.code                 AS plan_code,
  s.status               AS sub_status,
  p.realtime,
  p.seat_limit,
  (SELECT count(*) FROM memberships m WHERE m.tenant_id = t.id) AS seats_used,
  p.scan_quota,
  COALESCE(uc.used, 0)   AS scans_used,
  COALESCE(g.granted, 0) AS topup_remaining,
  CASE WHEN p.scan_quota IS NULL THEN NULL
       ELSE p.scan_quota + COALESCE(g.granted,0) - COALESCE(uc.used,0)
  END                    AS scans_remaining,
  p.retention_months,
  p.features
FROM tenants t
LEFT JOIN subscriptions s
       ON s.tenant_id = t.id AND s.status IN ('trialing','active','past_due')
LEFT JOIN plans p
       ON p.id = COALESCE(s.plan_id, (SELECT id FROM plans WHERE code = 'free'))
LEFT JOIN usage_counters uc
       ON uc.tenant_id = t.id
      AND uc.metric = 'scans'
      AND uc.period_start = date_trunc('month', now())::date
LEFT JOIN (
  SELECT tenant_id, sum(remaining) AS granted
  FROM usage_grants
  WHERE metric = 'scans' AND remaining > 0
    AND (expires_at IS NULL OR expires_at > now())
  GROUP BY tenant_id
) g ON g.tenant_id = t.id
WHERE t.deleted_at IS NULL;

-- Cost guardrail. Catches both abuse and a runaway escalation loop by comparing a
-- tenant's real inference spend this period against what they actually pay.
CREATE VIEW v_tenant_cost_vs_price AS
SELECT
  e.tenant_id,
  date_trunc('month', e.created_at)::date AS period_start,
  count(*)                                AS runs,
  sum(e.cost_micros) / 1000000.0          AS cost_aud,
  max(p.price_cents) / 100.0              AS plan_price_aud,
  CASE WHEN max(p.price_cents) > 0
       THEN (sum(e.cost_micros) / 10000.0) / max(p.price_cents)
  END                                     AS cost_ratio
FROM extraction_runs e
JOIN tenants t ON t.id = e.tenant_id
LEFT JOIN subscriptions s ON s.tenant_id = t.id AND s.status IN ('trialing','active','past_due')
LEFT JOIN plans p ON p.id = COALESCE(s.plan_id, (SELECT id FROM plans WHERE code='free'))
WHERE e.status = 'succeeded'
GROUP BY e.tenant_id, date_trunc('month', e.created_at);

-- RLS: subscriptions, usage_counters and usage_grants are tenant-scoped (same policy
-- as section 13). plans is a public read, like tax_codes.
