-- 0009_review_locks
-- Human-review field locks
--
-- Source of truth. Generated by splitting docs/data-model.sql (verified
-- against PostgreSQL 17); the SQL below is that verified text unchanged.

-- -----------------------------------------------------------------------------
-- 15. Human review: edit, confirm, save
--
-- The reviewer is part of the data model, not a UI afterthought. Three guarantees:
--
--   1. WHAT THE MODEL SAID IS NEVER LOST. extraction_runs.raw_response keeps the
--      exact model output; document_field_corrections records every human edit as
--      (field_path, old_value, new_value, corrected_by, corrected_at).
--
--   2. A HUMAN EDIT OUTRANKS ANY LATER MACHINE RUN. Re-extraction (a better model,
--      a new prompt) flips documents.current_run_id — and would otherwise silently
--      overwrite a field a person had already fixed. documents.locked_fields holds
--      the field paths a human has confirmed or edited; the merge step on
--      re-extraction MUST skip them and raise a review_task where the new run
--      disagrees, instead of clobbering.
--
--   3. CONFIRMATION IS THE DRAFT -> POSTED TRANSITION. Editing a document changes
--      data; confirming it posts a balanced transaction to the ledger. They are
--      separate acts, separately audited, and only the second one moves the books.
-- -----------------------------------------------------------------------------

-- Enforce guarantee 2 in the database rather than trusting the merge code:
-- once a field is locked, a machine run cannot quietly unlock it. Only a human
-- action (review_status -> 'reviewed'/'rejected') may change locked_fields.
CREATE OR REPLACE FUNCTION assert_locked_fields_respected() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  removed text[];
BEGIN
  SELECT array_agg(f) INTO removed
  FROM unnest(OLD.locked_fields) AS f
  WHERE f <> ALL (COALESCE(NEW.locked_fields, '{}'));

  IF removed IS NOT NULL AND NEW.reviewed_at IS NOT DISTINCT FROM OLD.reviewed_at THEN
    RAISE EXCEPTION
      'locked fields % cannot be released by a machine run on document %; a human review must release them',
      removed, NEW.id
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_documents_locked_fields
  BEFORE UPDATE OF locked_fields ON documents
  FOR EACH ROW EXECUTE FUNCTION assert_locked_fields_respected();
