import { useState } from 'react';
import { Image, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Icon } from '@/components/Icon';

import type { DocumentView } from '@/api';
import { Body, Chip, Label, Small } from '@/components/ui';
import { formatAbn, formatAud, formatShortDate, numeric, radius, space, type, usePalette } from '@/theme';

/**
 * The original document, as proof.
 *
 * Under the ATO's rules an electronic copy of a receipt is only acceptable if
 * it is a "true and clear reproduction" of the paper, so the image — not the
 * extraction — is the record being kept. It is never cropped, enhanced or
 * regenerated by the app; the panel below displays it and nothing more.
 *
 * Where no photograph exists (every seeded document in this demo — the repo
 * ships no photographs), a FACSIMILE is drawn from the extracted lines and
 * labelled as such. That is a deliberate choice over showing a grey box: the
 * point of the screen is to check the reading against the paper, and a
 * reconstruction at least shows the shape of what was read. It is never
 * presented as the photograph.
 */

function Paper({ doc }: { doc: DocumentView }) {
  const p = usePalette();
  const mono = {
    fontFamily: 'monospace' as const,
    fontSize: 11,
    lineHeight: 17,
    color: '#1B2430',
  };

  return (
    <View style={{ backgroundColor: '#FBF8F2', padding: 18, gap: 2 }}>
      <Text style={[mono, { fontWeight: '700', fontSize: 13, textAlign: 'center' }]}>
        {doc.supplierName.toUpperCase()}
      </Text>
      {doc.supplierAbn ? (
        <Text style={[mono, { textAlign: 'center' }]}>ABN {formatAbn(doc.supplierAbn)}</Text>
      ) : null}
      <Text style={[mono, { textAlign: 'center' }]}>{formatShortDate(doc.issueDate)}</Text>
      {doc.isTaxInvoice ? (
        <Text style={[mono, { textAlign: 'center', fontWeight: '700', marginTop: 6 }]}>
          *** TAX INVOICE ***
        </Text>
      ) : null}

      <Text style={[mono, { marginTop: 8 }]}>{'-'.repeat(34)}</Text>
      {doc.lines.map((l) => (
        <View key={l.lineNumber} style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
          <Text style={[mono, { flex: 1 }]} numberOfLines={1}>
            {l.quantity > 1 ? `${l.quantity} x ` : ''}
            {l.description}
            {l.gstFree ? ' *' : ''}
          </Text>
          <Text style={mono}>{formatAud(l.amount)}</Text>
        </View>
      ))}
      <Text style={mono}>{'-'.repeat(34)}</Text>

      <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
        <Text style={[mono, { fontWeight: '700' }]}>TOTAL</Text>
        <Text style={[mono, { fontWeight: '700' }]}>{formatAud(doc.payableAmount)}</Text>
      </View>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
        <Text style={mono}>GST included</Text>
        <Text style={mono}>{formatAud(doc.taxAmount)}</Text>
      </View>
      {doc.lines.some((l) => l.gstFree) ? (
        <Text style={[mono, { marginTop: 6 }]}>* GST-free item</Text>
      ) : null}

      {/* The torn edge, so a facsimile never reads as a screenshot of a form. */}
      <View style={{ flexDirection: 'row', marginTop: 10, marginHorizontal: -18 }}>
        {Array.from({ length: 26 }).map((_, i) => (
          <View
            key={i}
            style={{
              flex: 1,
              height: 8,
              backgroundColor: '#FBF8F2',
              borderBottomLeftRadius: i % 2 ? 8 : 0,
              borderBottomRightRadius: i % 2 ? 0 : 8,
            }}
          />
        ))}
      </View>
      <View style={{ height: 0, backgroundColor: p.ground }} />
    </View>
  );
}

export function OriginalDocument({
  doc,
  localPages,
  onImageExpired,
}: {
  doc: DocumentView;
  /**
   * Every page of a just-finished capture, still on this device.
   *
   * Only the capture screen supplies this, and only for the document it just
   * shot — it is faster than a round trip and works before the upload has
   * even finished. Every other case, including this same document reopened
   * a minute later, pages through `doc.pages` instead (§3.1 of the multi-page
   * capture contract): the server hands back every stored page, in order, so
   * paging does not depend on anything still being on this device.
   */
  localPages?: string[];
  /**
   * `imageUrl` and every `pages[].imageUrl` are short-TTL signed URLs
   * (`/v1/images/:token`, ~15 minutes — §8 of the multi-page capture
   * contract), minted fresh on the fetch that produced this `doc`. Sit on
   * this screen past the TTL and the URL 404s — an EXPECTED state, not a
   * failure worth an alert. The fix is a fresh `DocumentView`, which only
   * the screen holding `doc` can go get; this component notices the broken
   * load and asks, rather than reaching for `api()` itself and duplicating
   * whatever the caller's own fetch already does.
   */
  onImageExpired?: (failedUrl: string) => void;
}) {
  const p = usePalette();
  const insets = useSafeAreaInsets();
  const [zoomed, setZoomed] = useState(false);
  const [pageIndex, setPageIndex] = useState(0);
  // URLs that failed to load THIS render generation. Keyed by the URL string
  // itself, not the page — a refetch hands back a brand new token at a new
  // URL, so it is never in this set and needs no explicit reset here.
  const [failedUris, setFailedUris] = useState<ReadonlySet<string>>(() => new Set());

  function handleImageError(uri: string) {
    setFailedUris((prev) => (prev.has(uri) ? prev : new Set(prev).add(uri)));
    onImageExpired?.(uri);
  }

  /** A candidate URL, unless it already failed this generation — then falsy, same as no photo. */
  function display(uri: string | null | undefined): string {
    return uri && !failedUris.has(uri) ? uri : '';
  }

  // `doc.pages` always has at least one entry, so "more than one" is the
  // right test for "worth paging through" — same test `localPages` uses.
  // Local wins when present: it is the page just captured, still faster than
  // asking the server to hand back what was just uploaded to it.
  const localPageUris = localPages && localPages.length > 1 ? localPages : null;
  const storedPageUris =
    !localPageUris && doc.pages.length > 1 ? doc.pages.map((page) => page.imageUrl) : null;
  const pages = localPageUris ?? storedPageUris;
  const pageCount = pages ? pages.length : 1;
  const rawPhoto = pages
    ? pages[Math.min(pageIndex, pages.length - 1)]
    : (doc.localImageUri ?? doc.imageUrl);
  const photo = display(rawPhoto);

  function goTo(index: number) {
    if (!pages) return;
    setPageIndex(Math.max(0, Math.min(index, pages.length - 1)));
  }

  return (
    <View style={{ gap: space.sm }}>
      <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
        <Label>Original document</Label>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: space.xs }}>
          {pageCount > 1 ? <Chip>{`Page ${pageIndex + 1} of ${pageCount}`}</Chip> : null}
          <Chip tone={photo ? 'accent' : 'neutral'}>{photo ? 'Photographed' : 'Facsimile'}</Chip>
        </View>
      </View>

      <Pressable
        accessibilityRole="imagebutton"
        accessibilityLabel={
          pageCount > 1
            ? `View page ${pageIndex + 1} of ${pageCount} full screen`
            : 'View the original full screen'
        }
        onPress={() => setZoomed(true)}
        style={{
          borderRadius: radius.lg,
          overflow: 'hidden',
          borderWidth: 1,
          borderColor: p.rule,
          backgroundColor: '#FBF8F2',
          maxHeight: 260,
        }}
      >
        {photo ? (
          <Image
            source={{ uri: photo }}
            style={{ width: '100%', height: 260 }}
            resizeMode="cover"
            accessibilityLabel="The photographed receipt"
            // A signed image URL is short-TTL by design — a load failure here
            // is routinely just the token having outlived its ~15 minutes,
            // not a broken record. Drop to the facsimile immediately rather
            // than a broken-image icon, and tell the caller so it can refetch
            // the document for a fresh URL.
            onError={() => handleImageError(photo)}
          />
        ) : (
          <View style={{ maxHeight: 260, overflow: 'hidden' }}>
            <Paper doc={doc} />
          </View>
        )}
      </Pressable>

      {/* A strip of every page, so paging through this document does not
          require a full-screen modal just to see there IS a page 2. */}
      {pages ? (
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={{ gap: space.sm }}
        >
          {pages.map((uri, i) => (
            // Keyed on index, not the URI: a stored document can legitimately
            // hold more than one page with an empty (facsimile) `imageUrl`,
            // and a duplicate key would drop one of them.
            <Pressable
              key={i}
              accessibilityRole="button"
              accessibilityLabel={`Show page ${i + 1} of ${pageCount}`}
              onPress={() => goTo(i)}
              style={{
                borderRadius: 6,
                overflow: 'hidden',
                borderWidth: 2,
                borderColor: i === pageIndex ? p.accent : p.rule,
              }}
            >
              {display(uri) ? (
                <Image
                  source={{ uri: display(uri) }}
                  style={{ width: 42, height: 56 }}
                  resizeMode="cover"
                  onError={() => handleImageError(uri)}
                />
              ) : (
                // Either the empty-string facsimile convention, or this exact
                // URL already 404'd this generation — same fallback either way.
                <View
                  style={{
                    width: 42,
                    height: 56,
                    backgroundColor: '#FBF8F2',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                >
                  <Text style={{ fontSize: 7, color: '#8A7F6E', fontWeight: '600' }}>FACSIMILE</Text>
                </View>
              )}
            </Pressable>
          ))}
        </ScrollView>
      ) : null}

      <Small>
        {photo
          ? 'Stored unmodified as the legal record. Tap to view full size.'
          : 'Reconstructed from the extracted lines — this demo ships no photographs. A real capture stores the original image unmodified. Tap to view full size.'}
      </Small>

      <Modal visible={zoomed} animationType="fade" onRequestClose={() => setZoomed(false)}>
        <View style={{ flex: 1, backgroundColor: '#0A0F16' }}>
          <ScrollView
            contentContainerStyle={{
              flexGrow: 1,
              justifyContent: 'center',
              padding: space.lg,
              paddingTop: insets.top + space.xl,
            }}
            maximumZoomScale={4}
            minimumZoomScale={1}
          >
            {photo ? (
              <Image
                source={{ uri: photo }}
                style={{ width: '100%', height: 560 }}
                resizeMode="contain"
                accessibilityLabel="The photographed receipt, full size"
                onError={() => handleImageError(photo)}
              />
            ) : (
              <View style={{ borderRadius: radius.md, overflow: 'hidden' }}>
                <Paper doc={doc} />
              </View>
            )}
          </ScrollView>
          <View
            style={{
              padding: space.lg,
              paddingBottom: insets.bottom + space.lg,
              backgroundColor: '#0A0F16',
              gap: space.sm,
            }}
          >
            {pageCount > 1 ? (
              <View style={{ flexDirection: 'row', gap: space.sm }}>
                <ModalButton
                  label="Previous"
                  disabled={pageIndex === 0}
                  onPress={() => goTo(pageIndex - 1)}
                />
                <ModalButton
                  label={`Page ${pageIndex + 1} of ${pageCount}`}
                  disabled
                  onPress={() => {}}
                />
                <ModalButton
                  label="Next"
                  disabled={pageIndex === pageCount - 1}
                  onPress={() => goTo(pageIndex + 1)}
                />
              </View>
            ) : null}
            {/* Explicit light-on-dark rather than the themed outline button:
                the viewer paints its own near-black ground in both themes, so
                a palette-coloured label disappears against it in light mode. */}
            <Pressable
              accessibilityRole="button"
              onPress={() => setZoomed(false)}
              style={({ pressed }) => ({
                paddingVertical: 14,
                borderRadius: radius.md,
                borderWidth: 1.5,
                borderColor: 'rgba(255,255,255,0.5)',
                backgroundColor: pressed ? 'rgba(255,255,255,0.12)' : 'transparent',
                alignItems: 'center',
              })}
            >
              <Text style={{ color: '#FFFFFF', fontWeight: '700', fontSize: 15 }}>Close</Text>
            </Pressable>
          </View>
        </View>
      </Modal>
    </View>
  );
}

/** A light-on-dark control for inside the full-screen viewer — see the note above `Close`. */
function ModalButton({
  label,
  onPress,
  disabled,
}: {
  label: string;
  onPress: () => void;
  disabled?: boolean;
}) {
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ disabled: !!disabled }}
      onPress={disabled ? undefined : onPress}
      style={({ pressed }) => ({
        flex: 1,
        paddingVertical: 10,
        borderRadius: radius.md,
        borderWidth: 1.5,
        borderColor: disabled ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.5)',
        backgroundColor: pressed && !disabled ? 'rgba(255,255,255,0.12)' : 'transparent',
        alignItems: 'center',
      })}
    >
      <Text
        style={{
          color: disabled ? 'rgba(255,255,255,0.35)' : '#FFFFFF',
          fontWeight: '700',
          fontSize: 13,
        }}
      >
        {label}
      </Text>
    </Pressable>
  );
}

/** The one-line verdict on whether the lines and the total agree. */
export function BalanceNote({ doc }: { doc: DocumentView }) {
  const p = usePalette();
  const sum = doc.lines.reduce((a, l) => a + Number(l.amount), 0);
  const difference = Number(doc.payableAmount) - sum;
  const balanced = Math.abs(difference) < 0.005;

  return (
    <View
      style={{
        flexDirection: 'row',
        alignItems: 'center',
        gap: space.sm,
        backgroundColor: balanced ? p.accentSoft : p.warnSoft,
        borderRadius: radius.md,
        paddingHorizontal: space.md,
        paddingVertical: 10,
      }}
    >
      <Icon name={balanced ? 'check' : 'alert'} size={16} color={balanced ? p.good : p.warn} />
      <Body style={{ flex: 1, color: balanced ? p.accent : p.warn }}>
        {balanced
          ? `${doc.lines.length} line${doc.lines.length === 1 ? '' : 's'} adding to ${formatAud(doc.payableAmount)}`
          : `Lines are ${formatAud(Math.abs(difference).toFixed(4))} ${
              difference > 0 ? 'short of' : 'over'
            } the ${formatAud(doc.payableAmount)} total`}
      </Body>
      <Text style={[type.small, numeric, { color: balanced ? p.accent : p.warn, fontWeight: '700' }]}>
        {formatAud(sum.toFixed(4))}
      </Text>
    </View>
  );
}
